// Auto-generated Go code from C++ source
// Generated by Hybrid Transpiler

package main

// ============================================================================
// Base class: Shape (pure virtual)
// ============================================================================

type Shape struct {
}

func NewShape() *Shape {
    return &Shape{}
}

// Interface definitions for inherited base classes

// Interface representing C++ base class: Shape
type Shape interface {
    Area() float64
    Perimeter() float64
    Draw()
}

// ============================================================================
// Derived class: Circle
// ============================================================================

type Circle struct {
    Radius float64
}

func NewCircle(r float64) *Circle {
    return &Circle{
        Radius: r,
    }
}

func (this *Circle) Area() float64 {
    // Method body:
    return 3.14159 * this.Radius * this.Radius
}

func (this *Circle) Perimeter() float64 {
    // Method body:
    return 2 * 3.14159 * this.Radius
}

func (this *Circle) Draw() {
    // Method body:
    // Draw a circle
}

// Interface definitions for inherited base classes

// Interface representing C++ base class: Shape
type Shape interface {
    Area() float64
    Perimeter() float64
    Draw()
}

// Circle implements Shape interface
// Verification (compile-time check):
var _ Shape = (*Circle)(nil)

// ============================================================================
// Derived class: Rectangle
// ============================================================================

type Rectangle struct {
    Width  float64
    Height float64
}

func NewRectangle(w, h float64) *Rectangle {
    return &Rectangle{
        Width:  w,
        Height: h,
    }
}

func (this *Rectangle) Area() float64 {
    // Method body:
    return this.Width * this.Height
}

func (this *Rectangle) Perimeter() float64 {
    // Method body:
    return 2 * (this.Width + this.Height)
}

func (this *Rectangle) Draw() {
    // Method body:
    // Draw a rectangle
}

// Interface definitions for inherited base classes

// Interface representing C++ base class: Shape
type Shape interface {
    Area() float64
    Perimeter() float64
    Draw()
}

// Rectangle implements Shape interface
// Verification (compile-time check):
var _ Shape = (*Rectangle)(nil)

// Usage example:
// func useShapes() {
//     var circle Shape = NewCircle(5.0)
//     var rectangle Shape = NewRectangle(4.0, 6.0)
//
//     fmt.Println("Circle area:", circle.Area())
//     fmt.Println("Rectangle area:", rectangle.Area())
// }
