// Auto-generated Rust code from C++ source
// Generated by Hybrid Transpiler

// Base class: Shape (pure virtual)
pub struct Shape {}

impl Shape {
    pub fn new() -> Self {
        Self {}
    }
}

// Trait implementations for inherited base classes

// Trait representing C++ base class: Shape
pub trait Shape {
    fn area(&self) -> f64;
    fn perimeter(&self) -> f64;
    fn draw(&self);
}

// ============================================================================
// Derived class: Circle
// ============================================================================

pub struct Circle {
    pub radius: f64,
}

impl Circle {
    pub fn new(r: f64) -> Self {
        Self { radius: r }
    }

    pub fn area(&self) -> f64 {
        // Method body:
        return 3.14159 * self.radius * self.radius;
    }

    pub fn perimeter(&self) -> f64 {
        // Method body:
        return 2.0 * 3.14159 * self.radius;
    }

    pub fn draw(&self) {
        // Method body:
        // Draw a circle
    }
}

// Trait implementations for inherited base classes

impl Shape for Circle {
    fn area(&self) -> f64 {
        // Method body:
        return 3.14159 * self.radius * self.radius;
    }

    fn perimeter(&self) -> f64 {
        // Method body:
        return 2.0 * 3.14159 * self.radius;
    }

    fn draw(&self) {
        // Method body:
        // Draw a circle
    }
}

// ============================================================================
// Derived class: Rectangle
// ============================================================================

pub struct Rectangle {
    pub width: f64,
    pub height: f64,
}

impl Rectangle {
    pub fn new(w: f64, h: f64) -> Self {
        Self {
            width: w,
            height: h,
        }
    }

    pub fn area(&self) -> f64 {
        // Method body:
        return self.width * self.height;
    }

    pub fn perimeter(&self) -> f64 {
        // Method body:
        return 2.0 * (self.width + self.height);
    }

    pub fn draw(&self) {
        // Method body:
        // Draw a rectangle
    }
}

// Trait implementations for inherited base classes

impl Shape for Rectangle {
    fn area(&self) -> f64 {
        // Method body:
        return self.width * self.height;
    }

    fn perimeter(&self) -> f64 {
        // Method body:
        return 2.0 * (self.width + self.height);
    }

    fn draw(&self) {
        // Method body:
        // Draw a rectangle
    }
}

// Usage example:
// fn use_shapes() {
//     let circle: Box<dyn Shape> = Box::new(Circle::new(5.0));
//     let rectangle: Box<dyn Shape> = Box::new(Rectangle::new(4.0, 6.0));
//
//     println!("Circle area: {}", circle.area());
//     println!("Rectangle area: {}", rectangle.area());
// }
